language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'sailor-validator' ]; then cd .. && eval "mv $currentfolder sailor-validator" && cd sailor-validator; fi
